# Generated by Django 5.2.2 on 2025-06-06 12:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descripcion',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
