# Generated by Django 5.2.2 on 2025-06-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='vendedor_id',
            new_name='vendedor',
        ),
    ]
